### ISSUE TITLE
Camera Position

### ISSUE THREAD

**Issue by dmercel3DUN** [UmbraSoftware/umbrajs-three#5]
Hi, I am trying to get to grips with this example and I am struggling to understand the structure of the scene to find the position of the camera.

I have created a new model that is at quite a different location to the shoe and I can't seem to position the camera near it.  

Please can you describe the way that umbraScene.position.set works, as I can't find that described anywhere in the docs, and also how this relates to camera.position.set

It is probably something obvious I am missing, but I would really appreciate some help on this.
Thanks.

**Comment by juhomarttila** [comment]
Both `umbraScene.position` and `camera.position` are inherited from three.js, so their documentation is here: [https://threejs.org/docs/#api/en/core/Object3D.position](https://threejs.org/docs/#api/en/core/Object3D.position).

Your issue might be that camera near/far planes are set to too small/large values and the objects fall out of the camera's view frustum.

These following helper functions might be helpful with positioning the camera, and setting the near/far planes:

```
function placeCameraPosition(camera, model) {
  let box = model.getBounds()
  let center = model.getCenter()
  let size = new THREE.Vector3()
  box.getSize(size)

  let sphere = new THREE.Sphere()
  box.getBoundingSphere(sphere)
  let diagonal = sphere.radius
  let p = center.clone()
  p.x += diagonal
  p.z += diagonal
  p.y += size.y

  camera.position.set(p.x, p.y, p.z)
  camera.lookAt(center)
}

// Sets the camera near and far clip planes to match model scale
function setCameraRange(camera, model) {
  const bounds = model.getBounds()
  const x = bounds.max.x - bounds.min.x
  const y = bounds.max.y - bounds.min.y
  const z = bounds.max.z - bounds.min.z
  const diagonal = Math.sqrt(x * x + y * y + z * z)

  camera.near = Math.max(0.01, Math.min(1.0, diagonal / 1e4))
  camera.far = Math.max(100, diagonal * 4)
  camera.updateProjectionMatrix()
}
```

**Comment by pvaananen** [comment]
Closing this as inactive. Feel free open another issue if the problem wasn't solved.
